### ISSUE TITLE
Panics when run

### ISSUE THREAD

**Issue by evanoberholster** [shamaton/msgpackgen#2]
I am very interested in your serialization library. I decided to try it out on a project and got this error. Any solution?

evan@localhost:~/go/src/models/image$ msgpackgen -input-file metadata.go -dry-run -v
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/shamaton/msgpackgen/internal/generator.getImportPath(0xc000016100, 0x3b, 0xc000016100, 0x3b, 0x0, 0x0)
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:118 +0x2bd
github.com/shamaton/msgpackgen/internal/generator.(*generator).setOutputInfo(0xc00007e3c0, 0x6e6ab4, 0x1, 0xc00007e3c0, 0x0)
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:131 +0xa5
github.com/shamaton/msgpackgen/internal/generator.(*generator).run(0xc00007e3c0, 0x7ffee3b3d49e, 0xb, 0x6e6ab4, 0x1, 0x6ed89e, 0x16, 0xc000010100, 0x740180, 0xc00000e020, ...)
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:166 +0x8c
github.com/shamaton/msgpackgen/internal/generator.Run(0x6e6ab4, 0x1, 0x7ffee3b3d49e, 0xb, 0x6e6ab4, 0x1, 0x6ed89e, 0x16, 0x1, 0x10001, ...)
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:102 +0x455
main.generate(...)
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/main.go:47
main.main()
        /home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/main.go:30 +0x145
```

**Comment by shamaton** [comment]
@evanoberholster 
Thank you for your interest!!
How is `GOPATH` in your environment?
And is your new package in `GOPATH`?

**Comment by evanoberholster** [comment]
@shamaton sorry for the delayed response. Hope that this helps, I realize it may be a configuration error on my part.

`go version go1.16.2 linux/amd64`

Yes the package is in my `GOPATH`. 

`evan@localhost:~/go/github.com/evanoberholster/photo/models/image$ go get -u github.com/shamaton/msgpackgen@v0.1.1`
go get: added github.com/shamaton/msgpackgen v0.1.1

`evan@localhost:~/go/github.com/evanoberholster/photo/models/image$ msgpackgen -input-file metadata.go -dry-run -v`
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/shamaton/msgpackgen/internal/generator.getImportPath(0xc000018080, 0x3b, 0xc000018080, 0x3b, 0x0, 0x0)
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:118 +0x2bd
github.com/shamaton/msgpackgen/internal/generator.(*generator).setOutputInfo(0xc000080460, 0x6ea2fd, 0x1, 0xc000066960, 0x98)
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:131 +0xa5
github.com/shamaton/msgpackgen/internal/generator.(*generator).run(0xc000080460, 0x7ffce812c79f, 0xb, 0x6ea2fd, 0x1, 0x6f074b, 0x16, 0x100, 0x743760, 0xc00000e020, ...)
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:166 +0x8c
github.com/shamaton/msgpackgen/internal/generator.Run(0x6ea2fd, 0x1, 0x7ffce812c79f, 0xb, 0x6ea2fd, 0x1, 0x6f074b, 0x16, 0x1, 0x10001, ...)
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/internal/generator/gen.go:102 +0x455
main.generate(...)
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/main.go:47
main.main()
	/home/evan/go/pkg/mod/github.com/shamaton/msgpackgen@v0.1.1/main.go:30 +0x145

**Comment by shamaton** [comment]
@evanoberholster 
This file path `~/go/github.com/evanoberholster/photo/models/image` seems not to be in GOPATH, if it is truth.
I tried with the same path and got the same error.

I've fixed the cause of the panic, so give it a try with the new version `v0.1.2`.
https://github.com/shamaton/msgpackgen/releases

And then your path modify to `~/go/src/github.com/evanoberholster/photo/models/image`, please.

**Comment by Jarred-Sumner** [comment]
I'm running into the same issue

Is there a chance this could be supported in directories outside the `GOPATH`? I keep a separate `$HOME/Code` folder since I write in other languages than go

**Comment by shamaton** [comment]
@evanoberholster @Jarred-Sumner 
I have changed to use `go.mod` with default behavior @ `v0.2.0`.
If you create `go.mod`, you can generate code regardless of using GOPATH.

Can you give it a try?
