### ISSUE TITLE
Generated code to decode `[][]byte` always decodes as empty

### ISSUE THREAD

**Issue by nosideeffects** [shamaton/msgpackgen#6]
All of the generated code looks correct to me except for the line immediately following the inner most loop:
```
vv = vv
```
Here, `vv` is the value of a correctly decoded `[]byte`, which should actually be assigned to the var `vvv`:
```
vvv = vv
```
Making this change manually after code-gen seems to produce correct decoding. I haven't spent much time locating where in the code generation I could make this fix, but you could probably find it more easily.

**Comment by shamaton** [comment]
Hi @nosideeffects .
Sorry for delay.

Fixed it now. #7 
Please update!! 😄
