### ISSUE TITLE
Panic when struct contains X,Y int

### ISSUE THREAD

**Issue by beiriannydd** [shamaton/msgpackgen#9]
(dlv) p field
github.com/shamaton/msgpackgen/internal/generator/structure.Field {
	Name: "Y",
	Tag: "Y",
	Node: *github.com/shamaton/msgpackgen/internal/generator/structure.Node nil,}

This is valid Go but causes a panic when running msgpackgen.

**Comment by shamaton** [comment]
Hi @beiriannydd 

Can you show me the actual code when it occurred panic?
